### ISSUE TITLE
UI-Grundgerüst

### ISSUE THREAD

**Issue by SneakyFriday** [SneakyFriday/VR-Projekt#11]
- Start Button
- Menu
- Quit Button

**Comment by unknowcrank** [comment]
UI Über den Gast hinzugefügt. 

Sobald der Gast spawned wird momentan ein "!" Dargestellt was so viel wie: "Ich will bestellen bitte" bedeuten soll. 
Interagiert der Kellner(Spieler) mit dem Gast so wird die Bestellung über sein Kopf angezeigt und das "!" gelöscht.
